//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelIncome
    {
        public int Id { get; set; }
        public int Room_num { get; set; }
        public int Residents { get; set; }
        public System.DateTime Date_in { get; set; }
        public System.DateTime Date_out { get; set; }
        public double Room_cost { get; set; }
        public double Services_cost { get; set; }
        public double Total { get; set; }
    }
}
