//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Res_serv
    {
        public string Id_res { get; set; }
        public int Id_serv { get; set; }
        public int Id_res_serv { get; set; }
    
        public virtual Reservation Reservation { get; set; }
        public virtual Services Services { get; set; }
    }
}
